version: '2'

services:
  nginx:
    build: ./docker/nginx
    container_name: nginx
    ports:
    - "${DOCKER_HTTP_PORT}:80"
    - "${DOCKER_HTTPS_PORT}:443"
    networks:
    - site
    volumes:
    - ./logs/nginx:/var/log/nginx
    - ./web:/var/www/web
    - /etc/timezone:/etc/timezone:ro
    - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
  php71-fpm:
    build:
        context: ./docker/php-fpm/
        dockerfile: ./Dockerfile
        args:
            APP_ENV: "${APP_ENV}"
    container_name: php71-fpm
    networks:
    - site
    volumes:
    - ./web:/var/www/web
    - /etc/timezone:/etc/timezone:ro
    - /etc/localtime:/etc/localtime:ro
    - ./logs/mail:/var/log/msmtp
    restart: unless-stopped
    environment:
        - APP_ENV=${APP_ENV}
  mysql:
    build:
        context: ./docker/mysql/
        dockerfile: ./Dockerfile
    container_name: mysql
    user: ${MYSQL_USER_ID}
    environment:
      MYSQL_DATABASE: site
      MYSQL_USER: site
      MYSQL_PASSWORD: xV1S1YQFLwL1
      MYSQL_ROOT_PASSWORD: ZVjS2YQaL6L1
    networks:
    - site
    volumes:
    - ./database:/var/lib/mysql
    - /etc/timezone:/etc/timezone:ro
    - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
  memcached:
    image: memcached:1.5-alpine
    container_name: memcached
    entrypoint:
    - memcached
    - --memory-limit=1024m
    - --max-item-size=32m
    restart: unless-stopped
    mem_limit: 1073741824
    cpu_shares: 512
    networks:
    - site
networks:
  site:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.1.0
