version: '2'

services:
  nginx:
    build: 
        context: ./nginx
        dockerfile: ./Dockerfile
        args:
            USER: "${USER}"
    container_name: "${PROJECT_PREFIX}nginx"
    ports:
    - "${DOCKER_HTTP_PORT}:80"
    - "${DOCKER_HTTPS_PORT}:443"
    networks:
    - site
    volumes:
    - ./nginx/logs:/var/log/nginx
    - ./sockets/php:/run/php
    - ./../public:/var/www/web
    - /etc/timezone:/etc/timezone:ro
    - /etc/localtime:/etc/localtime:ro
    - /etc/passwd:/etc/passwd:ro
    - /etc/group:/etc/group:ro
    restart: unless-stopped
    environment:
        - APP_ENV=${APP_ENV}

  php71-fpm:
    build:
        context: ./php-fpm/
        dockerfile: ./Dockerfile
        args:
            APP_ENV: "${APP_ENV}"
            USER: "${USER}"
    container_name: "${PROJECT_PREFIX}php71-fpm"
    networks:
    - site
    volumes:
    - ./../public:/var/www/web
    - /etc/timezone:/etc/timezone:ro
    - /etc/localtime:/etc/localtime:ro
    - ./mail/logs:/var/log/msmtp
    - ./sockets/mysqld:/var/run/mysqld
    - ./sockets/php:/run/php
    - /etc/passwd:/etc/passwd:ro
    - /etc/group:/etc/group:ro

    restart: unless-stopped
    #user: "${USER_ID}:${GROUP_ID}"
    environment:
        - APP_ENV=${APP_ENV}
  mysql:
    build: ./mysql/        
    container_name: "${PROJECT_PREFIX}mysql"
    environment:
      MYSQL_DATABASE: site
      MYSQL_USER: site
      MYSQL_PASSWORD: xV1S1YQFLwL1
      MYSQL_ROOT_PASSWORD: ZVjS2YQaL6L1
    networks:
    - site
    volumes:
    - ./mysql/database:/var/lib/mysql
    - /etc/timezone:/etc/timezone:ro
    - /etc/localtime:/etc/localtime:ro
    - ./sockets/mysqld:/var/run/mysqld
    - /etc/passwd:/etc/passwd:ro
    - /etc/group:/etc/group:ro
    restart: unless-stopped
    user: "${USER_ID}:${GROUP_ID}"
  memcached:
    image: memcached:1.5-alpine
    container_name: "${PROJECT_PREFIX}memcached"
    entrypoint:
    - memcached
    - --memory-limit=1024m
    - --max-item-size=32m
    restart: unless-stopped
    mem_limit: 1073741824
    cpu_shares: 512
    networks:
    - site
networks:
  site:
    driver: bridge
    ipam:
        driver: default
        config:
        - subnet: 172.16.1.0/24
